language: java
dist: bionic
before_install:
- openssl aes-256-cbc -K $encrypted_f8204cd0c8d1_key -iv $encrypted_f8204cd0c8d1_iv
  -in secretTests.tar.enc -out secretTests.tar -d
- tar -xf secretTests.tar
script: make build && make test
notifications:
  email:
    on_success: always
    on_failure: always
